### ISSUE TITLE
Feature request: Scheduler for adding new songs to playlist

### ISSUE THREAD

**Issue by profucius** [jakubito/spotify-release-list#10]
Would it be possible to add a feature to your app which sets an automated schedule for doing a Refresh and then Export of the songs to a playlist? This goes hand-in-hand with my other feature request of adding songs to a single playlist.

Both of these together would make it so that I never miss out on new songs from the artists that I like on Spotify. I don't always remember to load your app to do the refresh manually.

**Comment by jakubito** [comment]
I'm afraid this is out of the scope of this project. Exporting to a playlist is not a core feature and it's meant to be used manually for smaller, filtered data. The idea behind this app is to have a clean interface showing individual releases instead of going through a playlist with massive amount of tracks being added to every day. There is also a technical limitation - everything is running locally on your device and that makes 100% automation impossible since there is no server running non-stop in the background.

There is #3 which will introduce background refresh and browser notifications. You may find it useful when it's done (there are a few obstacles I'm still trying to figure out)

**Comment by profucius** [comment]
Just to clarify before you fully close this out, perhaps a misunderstanding. My goal would be to automate this workflow using a macro tool on my computer.

Currently, I already have my macro tool load your app inside a webkit browser app I've created just for your app, and then it carries through a series of screen clicks and keyboard shortcuts to 1. Refresh, 2. Export, and 3. Copy the playlist URL.

With your addition of feature #9 I would be able to have the same URL persist across Refresh/Exports. And with the addition of this feature, I would no longer need the macros to be running. I would simply load your app in my webkit browser previous to the scheduled time, your app would run the Refresh and Export automatically.

Alternative to "scheduling" perhaps you would consider adding an option in the settings to auto-Refresh and a second one to auto-Export upon app load?

If these features are still out of scope, I can continue using my own macro tools for these automations, as long as we can get #9 for using the same playlist URL for subsequent Exports. Thanks!
