### ISSUE TITLE
Compilations show even if deselected in options

### ISSUE THREAD

**Issue by Mookiies** [jakubito/spotify-release-list#11]
Even when I exclude compilations a ton of them end up showing in the results. Some of these albums seem to be labeled explicitly by spotify as compilations which made me suspect this is a bug? 

Filtering by various artists does an excellent job of getting rid of them so that also made me wonder if this is an issue that someone tried to solve and ended up with a hack-ish solution?

Below is an example:
![image](https://user-images.githubusercontent.com/22333355/104396646-ecbaf080-54ff-11eb-852c-6ecb1dd805d5.png)
![image](https://user-images.githubusercontent.com/22333355/104396680-00feed80-5500-11eb-9a33-02d73945e3be.png)

![image](https://user-images.githubusercontent.com/22333355/104396660-f5abc200-54ff-11eb-844d-4d05f86da682.png)

**Comment by Mookiies** [comment]
Album info in case it is useful:
```
spotify:album:3NIjbnvM8NKJD6kcL3GIVn
https://open.spotify.com/album/3NIjbnvM8NKJD6kcL3GIVn?si=uG-eWSnJTvejOTrcZJzxEg
```

**Comment by jakubito** [comment]
This is because `album_group` field is used to categorize releases. Regarding the compilation you posted, Spotify API returns `appears_on` for artists you follow (Ice Cube, No Doubt, UB40), therefore the compilation is saved under "Appearances". I admit this is a bit confusing, but it's not a bug. The various artists filter has been added to work around this.

Difference between `album_group` and `album_type` (from Spotify docs):

![image](https://user-images.githubusercontent.com/8123702/104509318-5ab5f500-559e-11eb-830f-212cb5e1d228.png)

**Comment by Mookiies** [comment]
👍 Makes sense that its an API limitation so not much can be done. The workaround works great to filter them out anyways. 

Only suggestion I can think of is maybe adding some sort of text if compilations are deselected as the workaround may be hard to find.
