### ISSUE TITLE
Track didn't appear despite being released

### ISSUE THREAD

**Issue by KatyLB** [jakubito/spotify-release-list#2]
So, I'm not sure if this is a bug, but because the list is supposed to catch everything I'm going to report it anyway.

Today The Strokes released a new song called Bad Decisions. It's on Spotify [here](https://open.spotify.com/track/6e2pJqucDMxbp061B40r6O). I follow them, but it didn't appear on the list for today, despite refreshing. For some reason it didn't catch it.

**Comment by jakubito** [comment]
Hi @KatyLB,

Thank you for the bug report. I just tried following The Strokes, refreshing the list and it shows up correctly. Can you please try again and see if the issue still exist? 

I think the problem is on Spotify end - there are times when Spotify endpoints return an error for no reason. It's pretty rare and the error lasts only for a few minutes, but it can happen.

<img width="795" alt="image" src="https://user-images.githubusercontent.com/8123702/74765565-b36af980-5238-11ea-9c1b-1a577c6c4f3f.png">

**Comment by KatyLB** [comment]
I tried again, and it still isn't showing. I tried unfollowing and following as well.

**Comment by KatyLB** [comment]
Actually, now it is showing. Not sure if unfollowing/refollowing is what helped (which wouldn't be useful for tracking) or if it just showed eventually. It took two refreshes to appear, though...

**Comment by jakubito** [comment]
Good to know it's showing up now. I think unfollowing/refollowing does not have any impact and  this issue is related to https://github.com/spotify/web-api/issues/1311

The way it's working now is actually intended - when Spotify fails to return data for specific artist, the app suppresses the error and shows the rest of data.

I believe this is Spotify Web API bug and there's not much I can do here @KatyLB 😕
