### ISSUE TITLE
Feature request: Add notification of new release

### ISSUE THREAD

**Issue by livioavalle** [jakubito/spotify-release-list#3]
Hi, i really like and enjoy the app. 
I think that the app will be better with a sort of system that notify the new release, directly from chrome or maybe something like a telegram bot? It can be a very useful addition, so the user don't miss new release. Thanks and i appreciate your job.✌

**Comment by capellavacancies** [comment]
Usually I hate browser notifications but this is the only kind of notification I'd love to receive.

Thanks for the recent update
ps
If you add this feature please don't forget about firefox support

**Comment by protonize** [comment]
I don't think it's really neccesary. Releases are updating when it's 0:00 in your country so you'll get all of them in a moment.

**Comment by livioavalle** [comment]
> I don't think it's really neccesary. Releases are updating when it's 0:00 in your country so you'll get all of them in a moment.

That's not the point. With notifications, you don't need to open the site to find out if new songs have been released. Without notifications every day I should open the site. For me it's also a like a reminder, otherwise I would often forget to open the site.

**Comment by jakubito** [comment]
Hello, thank you for your suggestion.

I've been asked to implement notifications before, but due to technical limitations, it wasn't quite possible (implicit grant flow returns tokens valid only for 1 hour). I did some new research recently and it seems that Spotify now supports [PKCE Authorization Code Flow](https://developer.spotify.com/documentation/general/guides/authorization-guide/#authorization-code-flow-with-proof-key-for-code-exchange-pkce) which returns refreshable access tokens (a requirement for background syncing). So technically, it should be possible to do a refresh in the background and to send a browser notification once a day.

I personally don't miss notifications but I can see it would be a useful feature to have. I'm gonna keep this issue updated in case of any updates or issues encountered 👌

**Comment by livioavalle** [comment]
Perfect, i will wait for it

**Comment by morningscifi** [comment]
An e-mail digest of new albums from my followed artists would be amazing, too. It's really what I've wanted from Spotify all along: a plain weekly or biweekly e-mail that tells me which of my followed artists has a new full length album.

However, I could also just send myself a weekly e-mail that reminds me to check your website. I'm hesitant to suggest any changes, since I believe the site is nearly perfect exactly way it is now. I'm so happy you made it.

**Comment by jakubito** [comment]
@morningscifi Thank you.

I'm afraid e-mail notifications are out of the scope of this project. The biggest blocker is the fact it's a client-only application. That means it can only do background checks while the website is actually running in a browser tab. Therefore, it can't do anything while your computer is turned off. This is a decision I made at the beginning based on my personal needs. It would be time-consuming to introduce new server-side features on my own. Sorry. 

For this reason, I'm going ahead with browser notifications because I think they make more sense in this context.

**Comment by livioavalle** [comment]
> @morningscifi Thank you.
> 
> I'm afraid e-mail notifications are out of the scope of this project. The biggest blocker is the fact it's a client-only application. That means it can only do background checks while the website is actually running in a browser tab. Therefore, it can't do anything while your computer is turned off. This is a decision I made at the beginning based on my personal needs. It would be time-consuming to introduce new server-side features on my own. Sorry. 
> 
> For this reason, I'm going ahead with browser notifications because I think they make more sense in this context.

Are you already working on it?

**Comment by jakubito** [comment]
@livioavalle Not yet, I've been busy. I'm hoping for early next year

**Comment by jakubito** [comment]
Blocked by #18

**Comment by jakubito** [comment]
Hello, background auto refresh and notifications are now included in [v2.0.0](https://github.com/jakubito/spotify-release-list/releases/tag/v2.0.0). Unfortunately, these features are not available on phones because of the limitations of being a client-only web app.
