### ISSUE TITLE
Signing in on spotifyreleaselist.netlify.app is broken

### ISSUE THREAD

**Issue by JeffreyThiessen** [jakubito/spotify-release-list#36]
The following steps were taken to encounter this problem.

1. Click the Login with Spotify button
2. Sign in with spotify and agree
3. get redirected back to the app, but the following error occurs
![image](https://user-images.githubusercontent.com/16961365/172452258-28a30ab1-ceb7-40c1-ad29-febfb4edc45e.png)

I also captured the console errors
![image](https://user-images.githubusercontent.com/16961365/172452580-9b1fcc2a-425f-4bf8-943f-4e9bdddb2973.png)

Google chrome is also showing the following issue on the site
```
Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform

A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.

To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData. 

Note that for performance reasons, only the first access to one of the properties is shown.

AFFECTED RESOURCES 
1 source 
common.js:1
```

This blog post has some more information on the chrome changes that are likely the source of the issue
https://blog.chromium.org/2021/09/user-agent-reduction-origin-trial-and-dates.html

**Comment by JeffreyThiessen** [comment]
This seems to be a chromium only issue, as I can sign in on Firefox.

**Comment by jakubito** [comment]
I have tested the app in Chromium and it works just fine. `ERR_BLOCKED_BY_CLIENT` error indicates the request is blocked by a browser extension. Do you use any privacy-related extensions? I had a person who reported the same problem before and it turned out to be an extension called "Privacy Badger" [that blocks all communication to Spotify API](https://github.com/EFForg/privacybadger/issues/137).

Please disable all extensions and try again. When you find out which extension is causing the problems, try adding an exemption for the app
