### ISSUE TITLE
Not showing me all releases anymore

### ISSUE THREAD

**Issue by mockerianer** [jakubito/spotify-release-list#4]
Hi Jakub! Unfortunately the app doesn't show me all releases anymore since yesterday evening. I have it open in my Safari on my Mac and I use it as an app on my Samsung Phone. Do you have any idea why this happens? I cleared my cache already but no idea otherwise. I really need this app as it helps me run a music blog so much! Thanks a million!

**Comment by jakubito** [comment]
Hi @mockerianer!

I'm sorry you are experiencing issues. I have a few questions to start with:

- does it affect all artists or just a single one? What exactly is missing?
- do you get different results on your phone compared to desktop?
- are you runnning `v1.7.6`?
- do you get any errors in [javascript console](https://balsamiq.com/support/faqs/browserconsole/)?

Thank you for your cooperation, we'll figure this out together 👌

**Comment by mockerianer** [comment]
Thanks a million for answering so quickly! 
Let's figure this out! 

My phone version seems to be back to normal! 
Safari browser is only showing me 2 artists out of 700 that I follow for the past month and for Friday 20.11. it is showing me only two releases, whilst my phone is showing me 50. 

Yes, it says version 1.7.6 on Safari. 

I just tried on Chrome and that seems ok actually! 
83 errors in javascript console for Safari!

Hope you can make sense of this. I don't because I don't write code :)

**Comment by jakubito** [comment]
I just tried it in desktop Safari and I'm not seeing any errors. I'm getting the same results no matter what browser or device I test it on 🤔

Can you please post a screenshot of the console so I can see the errors? Thanks!

**Comment by mockerianer** [comment]
No problem! 
<img width="1280" alt="Bildschirmfoto 2020-11-21 um 22 17 00" src="https://user-images.githubusercontent.com/74825320/99888815-5c6ed680-2c47-11eb-89ff-bba0761623ba.png">

**Comment by jakubito** [comment]
These errors are actually expected - status **429** only means the browser has to wait a couple of seconds before firing more requests. I don't see any relevant errors being thrown.

Can you please try to disable all Safari extensions, [clear all website data](https://www.whatismybrowser.com/guides/how-to-clear-cookies-browsing-history-and-cache/safari) and try again? Also, make sure you have the same settings (album types, time period and market) across devices when comparing results.

Let me know!

**Comment by ghost** [comment]
I have a same problem. If I have the Appearence box checked then the list is showing me all releases. Even those who only have one artist for example the new King Gizzard & The Lizard Wizard or Shygirl album. If I uncheck the Appearence box these albums are gone. But they should be there, because it's not an appearence right?
Maybe spotify changed something with the meta data.

I hope I could help a little and thanks for the great support! :)

**Comment by MattSuda** [comment]
I have been using this app for several months now and I really enjoy using it. I follow tons of artists and it makes the job of keeping up with new music easier. I've linked to this app in the Spotify Community on my idea post since Spotify has not included a feature like this many years after the post. But I am glad you made this app because anything Spotify would have built wouldn't have been this advanced for an advanced user like me.

Yesterday when I refreshed the feed I was missing tons of new releases as well since this new version. Checked and I am on v1.7.6

The releases list in this update is much shorter than normal for the 1 year option (from the last time my 1 year list showed before this update) and when I search using CMD + F or using the new filter feature for an artist that had for sure released an album earlier in the year, that artist no longer shows up for any new releases at all this year when I know they had at least 2 and it showed in the list before.

This seems to be affecting many artists as when I scroll through the months, there are hardly any new releases that are being listed each week. It's like it's only showing a small amount of the total artists I follow.

Number of artists I am following: Around 2,300
What I tried: Deleted all data and started from scratch, and I also tried it in a total new browser instance with no prior data, and still the same issue
API Tested: I tried another Spotify API app and it was able to pull all of the artists I am following so no error in pulling the following list that I can see

**These are my settings using Google Chrome:**

Request:
Albums: Yes
Singles: Yes
Compilations: Yes
Appearances: No

Time Period: Past Year

Market: Tried account country (default) and United States -- pretty much the same results

Theme: Default


**Below are my findings and what seems to work as a work around for now:**

I tried it with "appearances" checked like the previous user in this thread mentioned and I am seeing what I think to be the releases I was missing but it also includes tons of spam. (more on that below)

Was there a change made so that these releases now only show when "appearances" box is checked? These releases showed in the feed just fine before the update with this box unchecked. Unfortunately it could be that the new algorithm might be at fault here. It says in the update it's supposed to show more releases now, but it was showing more before this update, now it's showing less. With the settings I am using that is. It might be different for different settings. It seems to me that any release that has an appearance by an artist in addition to the primary artist is being seen as an appearance by the artist you follow so that is why it only shows with the "appearances" box checked. 

The main reason I don't have appearances checked is that it always spams my feed with compilations which are just releases that have a ton of tracks on them from many different artists for no good reason. Since artists I follow "appear" on them they will end up showing. There are so many of these that I had to uncheck appearances. It seems the actual "complication" check box is if the artist you follow has released a compilation of their own.

For example when I turn on "appearances" these are some of the many spam releases I see in my feed:
https://open.spotify.com/album/6XkDr00dMvkdDNFYaJJVNw
https://open.spotify.com/album/2xyldZva11NEAtKIppe0ln
https://open.spotify.com/album/2qaST3gWF7UuyMCmfZ6Vc0
https://open.spotify.com/album/71X1g66MCMQtzTLg02jpVK
https://open.spotify.com/album/5nuZLgOA1uQJcUJu0hibg9
https://open.spotify.com/album/0UVExIe8OBcSyEoJt7aKQQ

Is there anyway to improve the app so that it can filter out and exclude "compilations" that artists you follow "appear on" ? That would probably be the best way to deal with this since any label can end up doing this. Or filter out to exclude "compilations" that artists you follow "appear on" that are released by "UMG label" if there is metadata for label ? -- UMG label seems to be the biggest offender of these type of generic spam compilations.  I really do not like to see these compilations from UMG and other labels in the Spotify app when I check the "appears on" section of an artist's page. If there was a way to hide those in this app it would be awesome since Spotify doesn't offer a way to hide them in their app.

When I try it with "compilations" not selected and "appearances" selected, these spam compilations still show up in the feed since artists I follow "appear" on these compilations. So having "appearances" selected solves this issue as a work around for the missing releases but it's not pleasant if you follow artists that are included on these frequently released spam compilations.

**Comment by MattSuda** [comment]
I think I found what the problem is. For my settings I usually have "albums, singles, and compilations" turned on, but I usually have "appearances" turned off. I tested with "albums and singles" turned on ONLY and it seems to be working correctly now with only "albums and singles" selected. (It appears to be fine with this work around, not 100% sure though)

So until that's fixed that's the work around I suggest trying. Although if you care about compilations released by an artist, then these would not show for now.

I would still like to know if there is a way to improve the app and have the "appearances" box checked with a way to show the releases the followed artists appear on, but exclude the compilation albums they appear on. I see in the filter options there is an album and single selection. Maybe adding a compilation option to that filter so I can go into the filters and choose only albums and single so that way no compilations will show up if an artist I follow appears on them. Or maybe next to the appearances box an option to exclude appearances on compilations would be better. (especially if you still want to see an artist's own compilation that would show with the regular compilation box) There might be several different ways to solve this problem. I hope you can find a good solution for it.

**Comment by sc113** [comment]
Yeah, in the latest update compilation checkbox stopped working well. It just doesn't include compilations anymore as it was before. 
Compilations filter is just gone (with enabled compilations in the settings). And when compilations are enabled (with appereances disabled) in the settings - most of albums\singles dissappear for some reason.

**Comment by jakubito** [comment]
Thank you all for your input, I've been able to identify the bug! It is indeed related to the "improvements" I made to the releases fetching algorithm recently. I'm gonna fix this ASAP, sorry for the inconvenience!

@MattSuda I know exactly what you're talking about. I have to go through those generic compilations every day. The problem is, Spotify defines them as appearances and there is no easy way to differentiate them from legit appearances. I like the idea of having a label blocklist. It doesn't fix the problem automatically but I think it's good enough. I will implement this when I have time 👍 Also, thank you for featuring the app on the Community page. I appreciate it 🙂

**Comment by jakubito** [comment]
@mockerianer @jokerbygithub @MattSuda @sc113 

This should be fixed now. Can you please test again? Make sure you are running `v1.7.7`

**Comment by MattSuda** [comment]
You're welcome! 🙂 

Yes it seems to be fixed now. Thank you! Also the improvements result in a much faster refresh time now. What used to take 10+ minutes for me with lots of artists now just takes a few minutes.  (especially on the "last year" option) 

Ah that's a bummer about the appearances on generic compilations. We might just have to put up with them then. I think a label block list could also block legit releases as well since you say there's no way to determine what is a real appearance and what is an appearance on compilations. We'll have to see how that works out. I also had an idea to maybe just block releases that contain the artist "Various Artists" since most of these have that in the artist list. The only true legit appearances that might have the "various artist" is like a movie soundtrack but I wouldn't be worried about missing those, and if I wanted to seem them I could just turn off the block and search for them. But I noticed the filter for keywords doesn't work for keywords that are in (     ) for example any album that has the title "Title Here (Original Motion Picture Soundtrack)" or "Title Here (Music From The Netflix Original Film)" means when I type "Soundtrack" or "Netflix" into the filter, it doesn't show up. I tried entering "(Original Motion Picture Soundtrack)" into the filter but only a few of them end up showing up. Not sure what exactly the filter is looking for (without digging through the code) but for certain keywords it doesn't currently work. For basic searching of artist and title without special characters it seems to work just right. As a work around I can scroll all the way to the bottom of the feed and then do a CMD + F for "Soundtrack" or "Netflix" and view them one by one that way.

Now that everything seems to be working and all the filter options are showing now -- what I think I will do it leave all of the boxes checked in the settings and then go through the list with "albums and singles" selected in the filter since the artists I follow rarely ever release a compilation I am interested in, then when I am done, I'll go back to the filters and only have "appearances" selected. The spam compilations will be mixed in with the appearances but they will be easier to skip over since less releases are showing at a time with the filter turned on. So the filters will make it more manageable at least.

**Comment by jakubito** [comment]
@MattSuda I think a new filter option for hiding releases that include "Various artists" is even better than the label blocklist. I believe it would filter out most of the rubbish 👍  Thanks!

I'm also happy it's faster for you now. I believe this is the fastest we can get with the current Spotify API.

**Comment by sc113** [comment]
Not being able to check 1.7.7, since I used it on spotifyreleaselist.netlify.app, and there's still 1.7.6.

Regarding VA albums, I guess the perfect would be to implemet a combination of both - the option to ignore VA releases from specific labels. In electronic music it's not a rare thing when the label release VA compilations with never-released-before tracks from different artists ([1](https://open.spotify.com/album/11oI2xEEE5HMSGGbtZQgiX), [2](https://open.spotify.com/album/38WXsuR1zs1TqP80Sqrwj8), [3](https://open.spotify.com/album/1j3gdHN0TltYwnOoHf4j0q)), so I'd like to not miss such VA releases.

While 95% of trashy VA releases in my list goes from "UMG Recordings, Inc.", and being able to block it would be just perfect.

**Comment by MattSuda** [comment]
It might take a few refreshes to get the latest version. 

That suggestion sounds great if it's possible. Blocking VA albums from certain labels.

**Comment by sc113** [comment]
Oh, right. It was not updating until I've deleted the cookies and now it's 1.7.7. Everything seems working just great now.

**Comment by jakubito** [comment]
Thank you again for reporting this

**Comment by mockerianer** [comment]
No problem! Thanks for fixing it!!
