### ISSUE TITLE
App non-functional

### ISSUE THREAD

**Issue by voukau** [jakubito/spotify-release-list#41]
The app is currently unresponsive (has been for at least a couple of days now). You cannot log in via Spotify, the app throws an ''Oops, something went wrong'' error message. Same thing happens if you hit "Refresh" when you're already logged in (the app allows you to log out though):

![Screenshot_20230116_132238](https://user-images.githubusercontent.com/47314278/212667018-ac25811e-e289-4a8a-bbd2-3911e728f7b8.png)

Seems like a call to Spotify API fails with a 503:

![Screenshot_20230116_132916](https://user-images.githubusercontent.com/47314278/212668282-095e156a-c105-4695-a34f-591c032bf318.png)

I guess your API key might've expired. Please, take a look, the app is :fire:

**Comment by jakubito** [comment]
Hello, thanks for the detailed report. I'm sorry it doesn't work for you. A few other people already contacted me about this in the past 2-3 days. 

I haven't been able to identify the problem. Everything works normally for me, which makes it difficult to debug. The 503 HTTP status code indicates it's an issue on Spotify's side. Maybe a server is down, or there's a maintenance happening? I haven't touched the app since the last release.

Can you please try again in a few days to see if it gets resolved? I'm afraid there's not much I can do at the moment. Let's wait and see what happens, I can try to escalate this with Spotify support if it persists

**Comment by nazarb25** [comment]
> Hello, thanks for the detailed report. I'm sorry it doesn't work for you. A few other people already contacted me about this in the past 2-3 days.
> 
> I haven't been able to identify the problem. Everything works normally for me, which makes it difficult to debug. The 503 HTTP status code indicates it's an issue on Spotify's side. Maybe a server is down, or there's a maintenance happening? I haven't touched the app since the last release.
> 
> Can you please try again in a few days to see if it gets resolved? I'm afraid there's not much I can do at the moment. Let's wait and see what happens, I can try to escalate this with Spotify support if it persists

Spotify had a massive outage a few days ago, after which your app stopped working. It may also be that they limited the number of requests to the API. I would recommend asking Spotify tech support what exactly is the problem.

**Comment by affinage** [comment]
the app wasn't working for me a few hours ago, but now it's ok. 

i suppose API is recovering (being recovered) from the outage, and Spotify is slowly rolling out its full workload capacity.

**Comment by voukau** [comment]
Yup, it's working as expected for me again too, same for my friends. Guess we can close this one :+1:

**Comment by jakubito** [comment]
Happy to see it's working now
