### ISSUE TITLE
Issue with location

### ISSUE THREAD

**Issue by ghost** [jakubito/spotify-release-list#44]
I always used New Zealand as location because then I can already see the releases of the next day which are not out yet in my time zone.
Since today that doesn't work anymore. It only shows the releases up to this day.
It's a very particular problem but to me it was always convenient. 
Maybe it's just an Spotify API change and you can't do anything about it.

**Comment by oliverdtsmith** [comment]
having the same issue, it's not just New Zealand either

**Comment by jakubito** [comment]
Unfortunately, it seems Spotify doesn't allow this anymore. Here's what the new [documentation](https://developer.spotify.com/documentation/web-api/reference/get-an-artists-albums) says about `market` parameter:

> If a valid user access token is specified in the request header, the country associated with the user account will take priority over this parameter.

Since the app uses user-access tokens for all API communication, there's not much I can do. I will remove the market option completely in the next update. Sorry for the inconvenience

**Comment by Jmhurtado86** [comment]
> having the same issue, it's not just New Zealand either

What if I scan using a VPN?

**Comment by jakubito** [comment]
@Jmhurtado86 That wouldn't help because they use the country associated with your Spotify account, which can't be changed with VPN
