### ISSUE TITLE
Version 3.6.1 keeps signing me out

### ISSUE THREAD

**Issue by jupiterine** [jakubito/spotify-release-list#50]
Hi. 

As the title says, since the last update, every few days I get logged out. I have to log in again and all my settings reset to default. It's getting very annoying.

I hope it can be fixed soon. Thank you in advance and happy holidays!

**Comment by jakubito** [comment]
Hello,

so far, I've not encountered any issues myself. I also didn't make any significant changes in 3.6.1, so it's difficult to say what the problem is. 

What OS and browser is this happening with? Have you tried turning off extensions, or using a different device/browser? It sounds like your local storage data gets deleted for some reason. It could be that the browser imposes some limitations because of not having enough free space, not sure... I will continue to do more testing, 

Thanks, happy holidays to you too

**Comment by jupiterine** [comment]
Hi, thanks for replying. I'm using Chrome 120 with Windows 10. 

I have plenty of space, so that's probably not it. I haven't tried a different device/browser, but this started happening since version 3.6.1, I don't know why. I haven't installed any new extensions, deleted caché or changed anything. It hasn't happened to me again since I posted about it, so that's a good sign. Hopefully it fixes itself.

Thanks for the help!
