### ISSUE TITLE
maybe not a real problem but coud be a good feature

### ISSUE THREAD

**Issue by xomaicol** [jakubito/spotify-release-list#55]
hi, i really love this service and because of this i'd like to help if it's possible; my "problem" is that sometime especially on friday when i refresh to see the new releases i see that some songs or albums are displayed at the day before but i don't understand why, maybe because midnight o'clock is seen as wednesday and not friday and because of that i miss some new releases. All that to suggest one thing, is possible to introduce a setting that makes the day change at 23:59 or at a time the user decide so we don't have this problem anymore? i'll leave a pic to make you understand better
![18cf3ecc02eaffa8fd323f8ac90416d6](https://github.com/jakubito/spotify-release-list/assets/169409875/106e0a1c-1e29-4a44-a3f7-c7a5a87fb6e1)

i hope that what i mean is understandable because eng is not my first language. 

much love and thanks for saving my life with this app

**Comment by jakubito** [comment]
Hey, thanks for the message, unfortunately there's not much I can do about this. To understand why, look at an example of album API response: `"release_date": "2024-04-15"` - as you can see, there's no information about time. All dates displayed are exactly what is provided by Spotify, without any modification, and I'd like to keep it that way. I recommend using the "New" filter, which should always show you what's been released since previous refresh.

Glad you like the app!
