### ISSUE TITLE
Not showing releases for day after

### ISSUE THREAD

**Issue by mockerianer** [jakubito/spotify-release-list#6]
Sorry Jakub, also just noticed that it doesn't show releases that are scheduled for day after anymore. 
It used to show me releases that are upcoming for day after the day before, like around 4pm or so. 
Any idea why that would be?

**Comment by jakubito** [comment]
@mockerianer You have to manually change the market setting to a country like New Zealand or Australia. By default, the country that is associated with your Spotify account is being used - that's why you can't see anything in advance. Beware, this may make some releases not playable with your account (some releases are region-locked).
